      - name: anilist
        uses: lowlighter/metrics@latest
        with:
          filename: anilist.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: ihamiru
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: characters, watching, reading, favorites
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_shuffle: yes

      - name: lines
        uses: lowlighter/metrics@latest
        with:
          filename: lines.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_lines: yes

      - name: icons
        uses: lowlighter/metrics@latest
        with:
          filename: icons.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: stars
        uses: lowlighter/metrics@latest
        with:
          filename: stars.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 8

      - name: isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year